# Generated by Django 3.2.5 on 2021-07-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webproject', '0002_auto_20210718_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tag',
            field=models.ManyToManyField(to='webproject.Tag'),
        ),
    ]
